//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSeguridad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/Mplace_Seguridad_WCF")]
    public partial class UsuarioDto : object
    {
        
        private string PasswordField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolDto", Namespace="http://schemas.datacontract.org/2004/07/Mplace_Seguridad_WCF")]
    public partial class RolDto : object
    {
        
        private string DescripcionField;
        
        private int IdEstadoField;
        
        private int IdRolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol
        {
            get
            {
                return this.IdRolField;
            }
            set
            {
                this.IdRolField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSeguridad.ISeguridad")]
    public interface ISeguridad
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridad/Registrar", ReplyAction="http://tempuri.org/ISeguridad/RegistrarResponse")]
        System.Threading.Tasks.Task<ServiceSeguridad.UsuarioDto> RegistrarAsync(ServiceSeguridad.UsuarioDto usuarioDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridad/ConsultarRoles", ReplyAction="http://tempuri.org/ISeguridad/ConsultarRolesResponse")]
        System.Threading.Tasks.Task<ServiceSeguridad.RolDto[]> ConsultarRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISeguridad/Login", ReplyAction="http://tempuri.org/ISeguridad/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(ServiceSeguridad.UsuarioDto usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISeguridadChannel : ServiceSeguridad.ISeguridad, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SeguridadClient : System.ServiceModel.ClientBase<ServiceSeguridad.ISeguridad>, ServiceSeguridad.ISeguridad
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SeguridadClient() : 
                base(SeguridadClient.GetDefaultBinding(), SeguridadClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISeguridad.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeguridadClient(EndpointConfiguration endpointConfiguration) : 
                base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), SeguridadClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeguridadClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeguridadClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SeguridadClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeguridadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceSeguridad.UsuarioDto> RegistrarAsync(ServiceSeguridad.UsuarioDto usuarioDto)
        {
            return base.Channel.RegistrarAsync(usuarioDto);
        }
        
        public System.Threading.Tasks.Task<ServiceSeguridad.RolDto[]> ConsultarRolesAsync()
        {
            return base.Channel.ConsultarRolesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(ServiceSeguridad.UsuarioDto usuario)
        {
            return base.Channel.LoginAsync(usuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISeguridad))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISeguridad))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64558/Seguridad.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SeguridadClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISeguridad);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SeguridadClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISeguridad);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISeguridad,
        }
    }
}
